// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: user.sql

package tutorial

import (
	"context"
)

const getUser = `-- name: getUser :one
select id, name, occupation, email, password, avatar_file_name, role, token, created_date, modified_date, created_by, modified_by from users limit 1
`

func (q *Queries) getUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Occupation,
		&i.Email,
		&i.Password,
		&i.AvatarFileName,
		&i.Role,
		&i.Token,
		&i.CreatedDate,
		&i.ModifiedDate,
		&i.CreatedBy,
		&i.ModifiedBy,
	)
	return i, err
}
